// Implements the network layer services for the library

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: communication.proto

package communication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_BROADCAST   MessageType = 0
	MessageType_JOIN        MessageType = 1
	MessageType_WRITE       MessageType = 2
	MessageType_WRITE_BATCH MessageType = 3
	MessageType_RECONSTRUCT MessageType = 4
	MessageType_TEST_HACSS  MessageType = 5
	MessageType_QC          MessageType = 6
	MessageType_QCREP       MessageType = 7
	MessageType_TIMEOUT     MessageType = 8
	MessageType_TQC         MessageType = 9
	MessageType_VIEWCHANGE  MessageType = 10
	MessageType_NEWVIEW     MessageType = 11
	MessageType_REC1        MessageType = 12
	MessageType_ECHO1       MessageType = 13
	MessageType_REC2        MessageType = 14
	MessageType_ECHO2       MessageType = 15
	MessageType_QCP2        MessageType = 16
	MessageType_QCP3        MessageType = 17
	MessageType_QCP4        MessageType = 18
	MessageType_QC2         MessageType = 19
	MessageType_QCBC        MessageType = 20
	MessageType_QCBCREP     MessageType = 21
	MessageType_QCREP2      MessageType = 22
	MessageType_QCBCFINAL   MessageType = 23
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "BROADCAST",
		1:  "JOIN",
		2:  "WRITE",
		3:  "WRITE_BATCH",
		4:  "RECONSTRUCT",
		5:  "TEST_HACSS",
		6:  "QC",
		7:  "QCREP",
		8:  "TIMEOUT",
		9:  "TQC",
		10: "VIEWCHANGE",
		11: "NEWVIEW",
		12: "REC1",
		13: "ECHO1",
		14: "REC2",
		15: "ECHO2",
		16: "QCP2",
		17: "QCP3",
		18: "QCP4",
		19: "QC2",
		20: "QCBC",
		21: "QCBCREP",
		22: "QCREP2",
		23: "QCBCFINAL",
	}
	MessageType_value = map[string]int32{
		"BROADCAST":   0,
		"JOIN":        1,
		"WRITE":       2,
		"WRITE_BATCH": 3,
		"RECONSTRUCT": 4,
		"TEST_HACSS":  5,
		"QC":          6,
		"QCREP":       7,
		"TIMEOUT":     8,
		"TQC":         9,
		"VIEWCHANGE":  10,
		"NEWVIEW":     11,
		"REC1":        12,
		"ECHO1":       13,
		"REC2":        14,
		"ECHO2":       15,
		"QCP2":        16,
		"QCP3":        17,
		"QCP4":        18,
		"QC2":         19,
		"QCBC":        20,
		"QCBCREP":     21,
		"QCREP2":      22,
		"QCBCFINAL":   23,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_communication_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_communication_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        int64                  `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Type          MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=communication.MessageType" json:"type,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_communication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_BROADCAST
}

func (x *Message) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type RawMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           []byte                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Result        bool                   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawMessage) Reset() {
	*x = RawMessage{}
	mi := &file_communication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMessage) ProtoMessage() {}

func (x *RawMessage) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMessage.ProtoReflect.Descriptor instead.
func (*RawMessage) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{1}
}

func (x *RawMessage) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *RawMessage) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

// Request with a request type and payload in bytes
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=communication.MessageType" json:"type,omitempty"`
	Request       []byte                 `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_communication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_BROADCAST
}

func (x *Request) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Request) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Empty response
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_communication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{3}
}

var File_communication_proto protoreflect.FileDescriptor

const file_communication_proto_rawDesc = "" +
	"\n" +
	"\x13communication.proto\x12\rcommunication\"g\n" +
	"\aMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\x03R\x06sender\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.communication.MessageTypeR\x04type\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\"6\n" +
	"\n" +
	"RawMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\fR\x03msg\x12\x16\n" +
	"\x06result\x18\x02 \x01(\bR\x06result\"m\n" +
	"\aRequest\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.communication.MessageTypeR\x04type\x12\x18\n" +
	"\arequest\x18\x02 \x01(\fR\arequest\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\a\n" +
	"\x05Empty*\xac\x02\n" +
	"\vMessageType\x12\r\n" +
	"\tBROADCAST\x10\x00\x12\b\n" +
	"\x04JOIN\x10\x01\x12\t\n" +
	"\x05WRITE\x10\x02\x12\x0f\n" +
	"\vWRITE_BATCH\x10\x03\x12\x0f\n" +
	"\vRECONSTRUCT\x10\x04\x12\x0e\n" +
	"\n" +
	"TEST_HACSS\x10\x05\x12\x06\n" +
	"\x02QC\x10\x06\x12\t\n" +
	"\x05QCREP\x10\a\x12\v\n" +
	"\aTIMEOUT\x10\b\x12\a\n" +
	"\x03TQC\x10\t\x12\x0e\n" +
	"\n" +
	"VIEWCHANGE\x10\n" +
	"\x12\v\n" +
	"\aNEWVIEW\x10\v\x12\b\n" +
	"\x04REC1\x10\f\x12\t\n" +
	"\x05ECHO1\x10\r\x12\b\n" +
	"\x04REC2\x10\x0e\x12\t\n" +
	"\x05ECHO2\x10\x0f\x12\b\n" +
	"\x04QCP2\x10\x10\x12\b\n" +
	"\x04QCP3\x10\x11\x12\b\n" +
	"\x04QCP4\x10\x12\x12\a\n" +
	"\x03QC2\x10\x13\x12\b\n" +
	"\x04QCBC\x10\x14\x12\v\n" +
	"\aQCBCREP\x10\x15\x12\n" +
	"\n" +
	"\x06QCREP2\x10\x16\x12\r\n" +
	"\tQCBCFINAL\x10\x172\xdd\b\n" +
	"\x04Send\x12<\n" +
	"\aSendMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12B\n" +
	"\vSendRequest\x12\x16.communication.Request\x1a\x19.communication.RawMessage\"\x00\x12>\n" +
	"\x04Join\x12\x19.communication.RawMessage\x1a\x19.communication.RawMessage\"\x00\x12C\n" +
	"\x0eRBCSendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12C\n" +
	"\x0eABASendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12C\n" +
	"\x0ePRFSendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12E\n" +
	"\x10ECRBCSendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12C\n" +
	"\x0eCBCSendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12E\n" +
	"\x10EVCBCSendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12D\n" +
	"\x0fMVBASendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12H\n" +
	"\x13RetrieveSendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12F\n" +
	"\x11SimpleSendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12D\n" +
	"\x0fEchoSendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12B\n" +
	"\rGCSendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12E\n" +
	"\x10HACSSSendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00\x12H\n" +
	"\x13HotStuffSendByteMsg\x12\x19.communication.RawMessage\x1a\x14.communication.Empty\"\x00B\x19Z\x17src/proto/communicationb\x06proto3"

var (
	file_communication_proto_rawDescOnce sync.Once
	file_communication_proto_rawDescData []byte
)

func file_communication_proto_rawDescGZIP() []byte {
	file_communication_proto_rawDescOnce.Do(func() {
		file_communication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_communication_proto_rawDesc), len(file_communication_proto_rawDesc)))
	})
	return file_communication_proto_rawDescData
}

var file_communication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_communication_proto_goTypes = []any{
	(MessageType)(0),   // 0: communication.MessageType
	(*Message)(nil),    // 1: communication.Message
	(*RawMessage)(nil), // 2: communication.RawMessage
	(*Request)(nil),    // 3: communication.Request
	(*Empty)(nil),      // 4: communication.Empty
}
var file_communication_proto_depIdxs = []int32{
	0,  // 0: communication.Message.type:type_name -> communication.MessageType
	0,  // 1: communication.Request.type:type_name -> communication.MessageType
	2,  // 2: communication.Send.SendMsg:input_type -> communication.RawMessage
	3,  // 3: communication.Send.SendRequest:input_type -> communication.Request
	2,  // 4: communication.Send.Join:input_type -> communication.RawMessage
	2,  // 5: communication.Send.RBCSendByteMsg:input_type -> communication.RawMessage
	2,  // 6: communication.Send.ABASendByteMsg:input_type -> communication.RawMessage
	2,  // 7: communication.Send.PRFSendByteMsg:input_type -> communication.RawMessage
	2,  // 8: communication.Send.ECRBCSendByteMsg:input_type -> communication.RawMessage
	2,  // 9: communication.Send.CBCSendByteMsg:input_type -> communication.RawMessage
	2,  // 10: communication.Send.EVCBCSendByteMsg:input_type -> communication.RawMessage
	2,  // 11: communication.Send.MVBASendByteMsg:input_type -> communication.RawMessage
	2,  // 12: communication.Send.RetrieveSendByteMsg:input_type -> communication.RawMessage
	2,  // 13: communication.Send.SimpleSendByteMsg:input_type -> communication.RawMessage
	2,  // 14: communication.Send.EchoSendByteMsg:input_type -> communication.RawMessage
	2,  // 15: communication.Send.GCSendByteMsg:input_type -> communication.RawMessage
	2,  // 16: communication.Send.HACSSSendByteMsg:input_type -> communication.RawMessage
	2,  // 17: communication.Send.HotStuffSendByteMsg:input_type -> communication.RawMessage
	4,  // 18: communication.Send.SendMsg:output_type -> communication.Empty
	2,  // 19: communication.Send.SendRequest:output_type -> communication.RawMessage
	2,  // 20: communication.Send.Join:output_type -> communication.RawMessage
	4,  // 21: communication.Send.RBCSendByteMsg:output_type -> communication.Empty
	4,  // 22: communication.Send.ABASendByteMsg:output_type -> communication.Empty
	4,  // 23: communication.Send.PRFSendByteMsg:output_type -> communication.Empty
	4,  // 24: communication.Send.ECRBCSendByteMsg:output_type -> communication.Empty
	4,  // 25: communication.Send.CBCSendByteMsg:output_type -> communication.Empty
	4,  // 26: communication.Send.EVCBCSendByteMsg:output_type -> communication.Empty
	4,  // 27: communication.Send.MVBASendByteMsg:output_type -> communication.Empty
	4,  // 28: communication.Send.RetrieveSendByteMsg:output_type -> communication.Empty
	4,  // 29: communication.Send.SimpleSendByteMsg:output_type -> communication.Empty
	4,  // 30: communication.Send.EchoSendByteMsg:output_type -> communication.Empty
	4,  // 31: communication.Send.GCSendByteMsg:output_type -> communication.Empty
	4,  // 32: communication.Send.HACSSSendByteMsg:output_type -> communication.Empty
	4,  // 33: communication.Send.HotStuffSendByteMsg:output_type -> communication.Empty
	18, // [18:34] is the sub-list for method output_type
	2,  // [2:18] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_communication_proto_init() }
func file_communication_proto_init() {
	if File_communication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_communication_proto_rawDesc), len(file_communication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communication_proto_goTypes,
		DependencyIndexes: file_communication_proto_depIdxs,
		EnumInfos:         file_communication_proto_enumTypes,
		MessageInfos:      file_communication_proto_msgTypes,
	}.Build()
	File_communication_proto = out.File
	file_communication_proto_goTypes = nil
	file_communication_proto_depIdxs = nil
}
